### PR TITLE
Updated the feedback image under issue# 13

### PR DESCRIPTION
**Pull request by Aini-Bashir**

### CODE REVIEW

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, I have merged it but can you change the slider 2 image again and then pushed back to me.

**Comment by Remy-Reveltek** [comment]
Because the second image has bad light

**Comment by Aini-Bashir** [comment]
Alright. I'll change the tone of the second image.

**Comment by Remy-Reveltek** [comment]
@Aini-Bashir, maybe change the whole image.

**Pull request merged**
